"""Added Market and Trade tables

Revision ID: 9014d13f2ff9
Revises: 1a793b69637c
Create Date: 2025-03-24 18:05:31.197559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9014d13f2ff9'
down_revision = '1a793b69637c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('outcome_yes_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('outcome_no_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('final_outcome', sa.String(length=10), nullable=True))
        batch_op.drop_index('ix_markets_status')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('created_at')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_markets_status', ['status'], unique=False)
        batch_op.drop_column('final_outcome')
        batch_op.drop_column('is_resolved')
        batch_op.drop_column('outcome_no_price')
        batch_op.drop_column('outcome_yes_price')
        batch_op.drop_column('created_by')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    op.drop_table('trades')
    # ### end Alembic commands ###
