"""GET and POST events and bets

Revision ID: d7ff0cc97ec6
Revises: 9014d13f2ff9
Create Date: 2025-03-24 19:35:19.066797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ff0cc97ec6'
down_revision = '9014d13f2ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint('markets_created_by_fkey', type_='foreignkey')
        batch_op.drop_column('final_outcome')

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('outcome',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.drop_constraint('trades_user_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_foreign_key('trades_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('outcome',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_outcome', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('markets_created_by_fkey', 'users', ['created_by'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
